$(function(){
    $("dd").css("display","none");
    $("dt").click(function(){
        if($("dd").css("display")=="block"){
            $("dd:not(:animated)").slideUp("slow");
        }else{
            $("dd").slideDown("slow");
        }
    });
});